### ISSUE TITLE
PlugIn wont load

### ISSUE THREAD

**Issue by derVicthor** [Lyliya/homebridge-ledstrip-ble#5]
Hey there,

I've added the plugin, but home bridge shows an error in the LOG

[1/5/2023, 11:40:14 AM] ====================
[1/5/2023, 11:40:14 AM] ERROR LOADING PLUGIN @lyliya/homebridge-ledstrip-ble:
[1/5/2023, 11:40:14 AM] TypeError: require(...) is not a function
    at Object.<anonymous> (/homebridge/node_modules/@lyliya/homebridge-ledstrip-ble/Device.js:1:44)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/@lyliya/homebridge-ledstrip-ble/index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
[1/5/2023, 11:40:14 AM] ====================

Anything I can do about that?

Thanks!

**Comment by Lyliya** [comment]
Hey, what version of homebridge / node are you using ?

The plugin stopped working recently because of dependencies to `noble` and i've been trying to fix it but with no success, I switch to Home Assistant using this plugin https://github.com/dave-code-ruiz/elkbledom to control my ledstrip. I dont know if i will update this plugin anymore

**Comment by derVicthor** [comment]
Hey there,

thanks for the quick response. I have noble 1.9.2-15 installed within the docker container - installed it manually just in case. Homebridge is on 1.6.0 with node 18.12.1.

**Comment by Lyliya** [comment]
Thats weird, i use the same version and the plugin initialize correctly

**Comment by derVicthor** [comment]
Could it be a problem with the dockerized Homebridge?

**Comment by Lyliya** [comment]
Ok got it, i release a patch, they change the way we need to load noble

**Comment by derVicthor** [comment]
Amazing! I'll wait for the patch then. Thanks for the quick solution <3

**Comment by Lyliya** [comment]
It's released 👌 

But as i said in first comment, the plugin is not stable at all, it work for me during months, and stopped working, i will probably try to update it, but probably not soon

as you use docker, dont forget to add those lines in your startup script (top right under terminal)
```
apt-get update && apt-get upgrade -y
apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
setcap cap_net_raw+eip $(eval readlink -f `which node`)
```
